### ISSUE TITLE
Unintuitive behavior of the March 1st version

### ISSUE THREAD

**Issue by Qrox** [SmartRSS/Smart-RSS#219]
1. For some reason, Chrome's March 1st update (2.24.0) automatically sets the "show only unread" option without telling the user, so it looks as if the feeds were removed.
2. Upon selecting a feed, the read items are only shown if you click on the unread count on the right, which is rather unintuitive and confusing, and again, there is not indication of this change of behavior to the user, so they might again think that unread items were removed.
3. If there is no unread items in a feed, you cannot even click the unread count to see the read items.

In case someone else also encounters the third problem: you can add this to the appearance - user css settings to show the unread counter so you can click it to see the full list:

```CSS
:not(.has-unread) > .source-counter {
    visibility: visible;
    color: rgba(0, 0, 0, 0.2);
}
```
